/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...catchAll]': RouteRecordInfo<'/[...catchAll]', '/:catchAll(.*)', { catchAll: ParamValue<true> }, { catchAll: ParamValue<false> }>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/contact/': RouteRecordInfo<'/contact/', '/contact', Record<never, never>, Record<never, never>>,
    '/partners/': RouteRecordInfo<'/partners/', '/partners', Record<never, never>, Record<never, never>>,
    '/partners/[id]': RouteRecordInfo<'/partners/[id]', '/partners/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/services/': RouteRecordInfo<'/services/', '/services', Record<never, never>, Record<never, never>>,
    '/services/design-construction/': RouteRecordInfo<'/services/design-construction/', '/services/design-construction', Record<never, never>, Record<never, never>>,
    '/services/information-technology/': RouteRecordInfo<'/services/information-technology/', '/services/information-technology', Record<never, never>, Record<never, never>>,
    '/services/logistic-supplychain/': RouteRecordInfo<'/services/logistic-supplychain/', '/services/logistic-supplychain', Record<never, never>, Record<never, never>>,
  }
}
