/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...catchAll]': RouteRecordInfo<'/[...catchAll]', '/:catchAll(.*)', { catchAll: ParamValue<true> }, { catchAll: ParamValue<false> }>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/contact/': RouteRecordInfo<'/contact/', '/contact', Record<never, never>, Record<never, never>>,
    '/homepage/': RouteRecordInfo<'/homepage/', '/homepage', Record<never, never>, Record<never, never>>,
    '/our-company/': RouteRecordInfo<'/our-company/', '/our-company', Record<never, never>, Record<never, never>>,
    '/partners/': RouteRecordInfo<'/partners/', '/partners', Record<never, never>, Record<never, never>>,
    '/services/': RouteRecordInfo<'/services/', '/services', Record<never, never>, Record<never, never>>,
    '/services/construction-and-design/': RouteRecordInfo<'/services/construction-and-design/', '/services/construction-and-design', Record<never, never>, Record<never, never>>,
    '/services/information-technology/': RouteRecordInfo<'/services/information-technology/', '/services/information-technology', Record<never, never>, Record<never, never>>,
    '/services/information-technology/[id]': RouteRecordInfo<'/services/information-technology/[id]', '/services/information-technology/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/services/logistics-and-supply-chain/': RouteRecordInfo<'/services/logistics-and-supply-chain/', '/services/logistics-and-supply-chain', Record<never, never>, Record<never, never>>,
  }
}
